CREATE TABLE bpis_data (
    row_id INT PRIMARY KEY,
    order_id VARCHAR(50),
    order_date DATE,
    ship_date DATE,
    ship_mode VARCHAR(50),
    customer_id VARCHAR(50),
    customer_name VARCHAR(255),
    segment VARCHAR(50),
    country VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    region VARCHAR(50),
    product_id VARCHAR(50),
    category VARCHAR(50),
    sub_category VARCHAR(50),
    product_name VARCHAR(255),
    sales FLOAT,
    quantity INT,
    discount FLOAT,
    profit FLOAT,
    order_year INT,
    order_month INT,
    month_year_str VARCHAR(20),
    price FLOAT,
    revenue FLOAT,
    aov FLOAT,
    margin_pct FLOAT,
    sales_prod FLOAT,
    profit_prod FLOAT,
    quantity_prod FLOAT,
    discount_prod FLOAT,
    price_prod FLOAT,
    profit_margin FLOAT,
    recency_days INT,
    frequency INT,
    monetary FLOAT,
    RFM_Score INT,
    CLTV_pred FLOAT
);
GO
